update to sling 47
apache/sling-org-apache-sling-jcr-webdav pull request #2
Opened 2022-04-30 08:02 UTC by ashokmca07

2022-05-11 09:39 UTC, rombert requested changes
The PR looks good, thanks @ashokmca07 ! The only change that I see as needed is the removal of the commons.osgi dependency, we no longer use it.

2022-05-11 09:39 UTC, rombert commented on bnd.bnd
> +Import-Package: org.apache.sling.commons.osgi, *
This should be removed completely, the dependency is no longer used.

2022-05-11 09:39 UTC, rombert commented on pom.xml
> +        <dependency>
This should be removed completely, the dependency is no longer used.

2022-05-12 05:21 UTC, ashokmca07 commented
Hi @rombert thanks for reviewing, Could you please review again?

2022-05-12 05:43 UTC, reschke commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
do not rely on EOL'd Jackrabbit versions

2022-05-12 05:44 UTC, reschke requested changes
Please do not reference EOLd Jackrabbit versions.

2022-05-12 06:53 UTC, ashokmca07 commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
Updated to the version `2.20.4` which is same like `sling-org-apache-sling-starter`

PS: I was thinking to use the latest version, but in past someone raised that we should use very least versions.

2022-05-12 11:59 UTC, rombert commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
I was probably the one talking about using versions that are as old possible :-)

The long-standing policy that we have is to use old versions so that OSGi imports are as relaxed as possible. Of course, deployers should follow good practices and use the latest version of libraries. This is what we do in the Sling Starter where we use the latest Jackrabbit and Oak artifacts.

I'd suggest that we leave the jackrabbit version untouched here, since upgrading the parent version does require it Would that work for you @reschke @ashokmca07 ?

2022-05-12 12:14 UTC, reschke commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
I just don't get what the reasoning here is. *Nobody* should be referring to a version that had at least 7 bug fix releases since.

2022-05-12 12:15 UTC, ashokmca07 commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
I am fine with older versions as long as its working fine and compiles. I just reverted to `2.14.3` 

PS: @rombert just upgraded the version from 2.14.2 to `2.14.3` because of the known issue  `org.apache.jackrabbit.vault.fs.api.RepositoryFactory is not an ImageIO SPI class`

2022-05-12 12:46 UTC, rombert commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
> I just don't get what the reasoning here is

The reasoning is that we should not force people deploying Sling apps to upgrade libraries if they don't have/want to. I went into a bit more detail in https://github.com/apache/sling-org-apache-sling-jcr-webdav/pull/2#discussion_r871292082 .

Which parts of this do you disagree with? And what negative impact do you see when using this particular version of the Jackrabbit libraries?

2022-05-12 12:51 UTC, reschke commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
But is that a reason to reference a version that has been obsolete for several years, and which will not see any security updates anymore?

I *could* understand if the choice was the latest release from the oldest stable branch (which would be 2.16.9).

2022-05-12 12:59 UTC, reschke commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
With 2.16.9:

~~~
[WARNING]

One or more dependencies were identified with known vulnerabilities in Apache Sling JCR WebDAV:

org.apache.sling.api-2.0.8.jar (pkg:maven/org.apache.sling/org.apache.sling.api@2.0.8, cpe:2.3:a:apache:sling:2.0.8:*:*:*:*:*:*:*, cpe:2.3:a:apache:sling_api:2.0.8:*:*:*:*:*:*:*) : CVE-2015-2944
org.apache.sling.auth.core-1.0.0.jar (pkg:maven/org.apache.sling/org.apache.sling.auth.core@1.0.0, cpe:2.3:a:apache:sling_auth_core_component:1.0.0:*:*:*:*:*:*:*) : CVE-2013-4390
org.apache.sling.jcr.api-2.0.6.jar (pkg:maven/org.apache.sling/org.apache.sling.jcr.api@2.0.6, cpe:2.3:a:apache:sling:2.0.6:*:*:*:*:*:*:*, cpe:2.3:a:apache:sling_api:2.0.6:*:*:*:*:*:*:*) : CVE-2015-2944
~~~

2022-05-12 13:08 UTC, reschke commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
My point being: by referencing thes obsolete versions we encourage users just to copy/paste the version numbers into their projects. Not good.

2022-05-12 13:09 UTC, kwin commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
IMHO that doesn’t matter as long as we don’t embed the vulnerable dependency. Sling in general recommends using the latest/greatest but does not force to (that is obligation of Jackrabbit). We only depend on the oldest dependency providing the necessary/used API

2022-05-12 13:13 UTC, reschke commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
> (that is obligation of Jackrabbit)

How so?

2022-05-12 13:26 UTC, kwin commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
By documenting supported versions (like in https://jackrabbit.apache.org/jcr/jackrabbit-roadmap.html) and doing announcements on the. mailing list. Both is properly done in this case :-)

2022-05-12 13:32 UTC, kwin commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
> IMHO there's absolutely no benefit in being relaxed here

There is a benefit for users not wanting to update to a newer (less vulnerable) JR version but want to use a newer SLING JCR WebDAV bundle (for whatever reason). Think about EOL products where upgrading the JCR implementation is not feasible ;-)

2022-05-12 14:17 UTC, rombert commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
I would say that in this case updating the JCR WebDAV bundle is feasible precisely because it frictionless - no new requirements. And I think the example is the right one to give - OSGi allows decoupling build-time from run-time dependencies. Let's not throw that away because we think we may get people who copy-paste and don't check in trouble.

At the same time, here is the list of changes to the manifest, generated using `bnd diff`

```
bnd diff --manifest org.apache.sling.jcr.webdav-2.3.9-SNAPSHOT.jar target/org.apache.sling.jcr.webdav-2.3.9-SNAPSHOT.jar
CHANGED    MANIFEST   <manifest>
 CHANGED    HEADER     Export-Package
  ADDED      CLAUSE     org.apache.jackrabbit.server
  CHANGED    CLAUSE     org.apache.jackrabbit.server.io
   REMOVED    PARAMETER  version:2.14.3
   ADDED      PARAMETER  version:2.20.4
 CHANGED    HEADER     Import-Package
  ADDED      CLAUSE     java.time.format
  ADDED      CLAUSE     org.apache.jackrabbit.server
  CHANGED    CLAUSE     org.apache.jackrabbit.util
   REMOVED    PARAMETER  version:[2.4,3)
   ADDED      PARAMETER  version:[2.5,3)
  CHANGED    CLAUSE     org.apache.jackrabbit.webdav
   REMOVED    PARAMETER  version:[1.1,2)
   ADDED      PARAMETER  version:[1.4,2)
  CHANGED    CLAUSE     org.apache.jackrabbit.webdav.server
   REMOVED    PARAMETER  version:[1.0,2)
   ADDED      PARAMETER  version:[1.2,2)
  CHANGED    CLAUSE     org.apache.jackrabbit.webdav.util
   REMOVED    PARAMETER  version:[1.0,2)
   ADDED      PARAMETER  version:[1.1,2)
  CHANGED    CLAUSE     org.apache.jackrabbit.webdav.version.report
   REMOVED    PARAMETER  version:[1.0,2)
   ADDED      PARAMETER  version:[1.1,2)
  CHANGED    CLAUSE     org.apache.jackrabbit.webdav.xml
   REMOVED    PARAMETER  version:[1.1,2)
   ADDED      PARAMETER  version:[1.2,2)
  CHANGED    CLAUSE     org.apache.tika.detect
   REMOVED    PARAMETER  version:[1.0,2)
   ADDED      PARAMETER  version:[1.27,2)
  CHANGED    CLAUSE     org.apache.tika.metadata
   REMOVED    PARAMETER  version:[1.0,2)
   ADDED      PARAMETER  version:[1.27,2)
  CHANGED    CLAUSE     org.apache.tika.mime
   REMOVED    PARAMETER  version:[1.2,2)
   ADDED      PARAMETER  version:[1.27,2)
 REMOVED    HEADER     Private-Package:org.apache.jackrabbit.server,org.apache.jackrabbit.webdav.simple,org.apache.sling.jcr.webdav.impl.handler,org.apache.sling.jcr.webdav.impl.helper,org.apache.sling.jcr.webdav.impl.servlets,org.apache.jackrabbit.webdav.jcr,org.apache.jackrabbit.webdav.jcr.lock
 ADDED      HEADER     Private-Package:org.apache.jackrabbit.webdav.simple,org.apache.sling.jcr.webdav.impl.handler,org.apache.sling.jcr.webdav.impl.helper,org.apache.sling.jcr.webdav.impl.servlets,org.apache.jackrabbit.webdav.jcr,org.apache.jackrabbit.webdav.jcr.lock
```

I find it misleading to say, for instance, "we require Tika 1.27 or newer", when we know that we can work with Tika 1.0 or newer.

2022-05-12 14:19 UTC, reschke commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
Why would we want to support people in using an ancient Tika version with known security vulnerabilities?

2022-05-12 14:47 UTC, kwin commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
Because people may want to run with an ancient Tika.

2022-05-12 14:49 UTC, rombert commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
> Why would we want to support people in using an ancient Tika version with known security vulnerabilities?

As I've said before, this is not our call. We should not dictate what versions customers use, they should be able to make informed decisions. This is more or less a rehash of the arguments we had for dependabot - https://cwiki.apache.org/confluence/display/SLING/Dependabot . We don't make blanket updates to the latest versions, we let our users decide.

2022-05-17 07:38 UTC, rombert commented on pom.xml
> +        <jackrabbit.version>2.14.3</jackrabbit.version>
I think we should merge this as-is. @reschke - please discuss on dev@sling any changes that think are needed on the Sling dependency policy. Thanks!

2022-05-17 07:38 UTC, merged